// frontend/apps/web/src/components/ScheduleGrid.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ScheduleEntry } from '@zhiheng/shared'

const props = withDefaults(defineProps<{
  entries: ScheduleEntry[]
  periods?: number
  dateMode?: boolean
  weekStart?: string
}>(), { periods: 8, dateMode: false, weekStart: '' })

const weekdayLabels = ['周一', '周二', '周三', '周四', '周五']
const headers = computed(() => weekdayLabels.map((label, index) => {
  const item = props.entries.find((entry) => entry.weekday === index + 1 && entry.lesson_date)
  let date = item?.lesson_date
  if (!date && props.dateMode && props.weekStart) {
    const day = new Date(`${props.weekStart}T00:00:00`)
    day.setDate(day.getDate() + index)
    date = [day.getFullYear(), String(day.getMonth() + 1).padStart(2, '0'), String(day.getDate()).padStart(2, '0')].join('-')
  }
  return { label, date: date?.slice(5) }
}))

function lesson(weekday: number, period: number) {
  return props.entries.find((entry) => entry.weekday === weekday && entry.period === period)
}
</script>

<template>
  <div class="schedule-wrap" role="region" aria-label="课程表" tabindex="0">
    <div class="schedule-grid">
      <div class="corner-cell"><span>节次</span><small>时间</small></div>
      <div v-for="header in headers" :key="header.label" class="day-head">
        <strong>{{ header.label }}</strong>
        <small v-if="dateMode">{{ header.date || '—' }}</small>
      </div>
      <template v-for="period in periods" :key="period">
        <div class="period-cell"><strong>{{ period }}</strong><small>第 {{ period }} 节</small></div>
        <div v-for="weekday in 5" :key="`${weekday}-${period}`" class="lesson-cell" :class="{ filled: lesson(weekday, period) }">
          <template v-if="lesson(weekday, period)">
            <strong>{{ lesson(weekday, period)?.subject_name }}</strong>
            <span>{{ lesson(weekday, period)?.teacher_name }}</span>
            <small v-if="lesson(weekday, period)?.room">{{ lesson(weekday, period)?.room }}</small>
          </template>
          <span v-else class="empty-mark">—</span>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.schedule-wrap { overflow:auto; border:1px solid var(--line); background:#fff; }
.schedule-grid { min-width:840px; display:grid; grid-template-columns:88px repeat(5,1fr); }
.corner-cell,.day-head,.period-cell,.lesson-cell { min-height:76px; border-right:1px solid var(--line); border-bottom:1px solid var(--line); }
.corner-cell,.day-head,.period-cell { display:flex; flex-direction:column; align-items:center; justify-content:center; background:#f7f9fc; }
.corner-cell span,.period-cell strong { color:var(--ink-950); font-size:13px; }
.corner-cell small,.period-cell small,.day-head small { margin-top:4px; color:var(--ink-500); font-size:10px; }
.day-head { min-height:54px; border-top:3px solid var(--graphite-950); }
.day-head strong { color:var(--ink-950); font-size:13px; }
.lesson-cell { padding:11px 12px; display:flex; flex-direction:column; justify-content:center; background:#fff; }
.lesson-cell.filled { border-left:3px solid var(--blue-600); background:#f8fbff; }
.lesson-cell strong { color:var(--ink-950); font-size:13px; }
.lesson-cell span { margin-top:5px; color:var(--ink-500); font-size:11px; }
.lesson-cell small { margin-top:3px; color:var(--blue-600); font-size:10px; }
.empty-mark { align-self:center; color:#d4dae3!important; }
.schedule-grid > :nth-child(6n) { border-right:0; }
@media print { .schedule-wrap { overflow:visible; border-color:#999; } .schedule-grid { min-width:0; } }
</style>

// frontend-react/src/components/ScheduleGrid.tsx
import type { ScheduleEntry } from '@/types'

const WEEKDAY_LABELS = ['周一', '周二', '周三', '周四', '周五']

interface ScheduleGridProps {
  entries: ScheduleEntry[]
  periods?: number
  /** 表头附加日期列（排考/走班日历用） */
  dateMode?: boolean
  weekStart?: string
  onLessonContextMenu?: (entry: ScheduleEntry, event: React.MouseEvent<HTMLDivElement>) => void
}

/** 课表大表：节次 × 星期 网格，适配打印 */
export default function ScheduleGrid({
  entries,
  periods = 7,
  dateMode = false,
  weekStart = '',
  onLessonContextMenu,
}: ScheduleGridProps) {
  const headers = WEEKDAY_LABELS.map((label, index) => {
    const weekday = index + 1
    const item = entries.find((e) => e.weekday === weekday && e.lesson_date)
    let date = item?.lesson_date
    if (!date && dateMode && weekStart) {
      const day = new Date(`${weekStart}T00:00:00`)
      day.setDate(day.getDate() + index)
      date = [
        day.getFullYear(),
        String(day.getMonth() + 1).padStart(2, '0'),
        String(day.getDate()).padStart(2, '0'),
      ].join('-')
    }
    return { label, date: date?.slice(5) }
  })

  const lesson = (weekday: number, period: number) =>
    entries.find((e) => e.weekday === weekday && e.period === period)

  const cells: React.ReactNode[] = []
  cells.push(
    <div key="corner" className="st-corner">
      <span>节次</span>
      <small>时间</small>
    </div>,
  )
  headers.forEach((h) => {
    cells.push(
      <div key={`head-${h.label}`} className="st-day-head">
        <strong>{h.label}</strong>
        {dateMode && <small>{h.date || '—'}</small>}
      </div>,
    )
  })
  for (let period = 1; period <= periods; period += 1) {
    cells.push(
      <div key={`period-${period}`} className="st-period">
        <strong>{period}</strong>
        <small>第 {period} 节</small>
      </div>,
    )
    for (let weekday = 1; weekday <= 5; weekday += 1) {
      const entry = lesson(weekday, period)
      cells.push(
        <div
          key={`lesson-${weekday}-${period}`}
          className={`st-lesson${entry ? ' filled' : ''}`}
          onContextMenu={entry && onLessonContextMenu ? (event) => onLessonContextMenu(entry, event) : undefined}
        >
          {entry ? (
            <>
              <strong>{entry.subject_name}</strong>
              <span>{entry.teacher_name}</span>
              {entry.room && <small>{entry.room}</small>}
            </>
          ) : (
            <span className="st-empty-mark">—</span>
          )}
        </div>,
      )
    }
  }

  return (
    <div className="schedule-table-wrap" role="region" aria-label="课程表" tabIndex={0}>
      <div className="schedule-table">{cells}</div>
    </div>
  )
}
